/*
 * I2C_types.h
 *
 *  Created on: Mar 10, 2023
 *      Author: Ahmed Hesham
 */

#ifndef I2C_I2C_TYPES_H_
#define I2C_I2C_TYPES_H_

typedef enum{
	I2C_RATE_400KHZ,
	I2C_RATE_100KHZ

}I2C_Bit_Rate_t;


typedef enum{
	START_TRANSMITTED=0x08,
	REAPEATED_START_TRANSMITTED=0x10,
	ADRESS_TRANSMITTED_W_ACK_RECIEVED=0x18,
	ADRESS_TRANSMITTED_W_NOT_ACK_RECIEVED=0x20,
	ADRESS_TRANSMITTED_R_ACK_RECIEVED=0x40,
	ADRESS_TRANSMITTED_R_NOT_ACK_RECIEVED=0x48,
	DATA_BYTE_TRANSMITTED_ACK_RECIEVED=0x28,
	DATA_BYTE_TRANSMITTED_NOT_ACK_RECIEVED=0x30,
	DATA_BYTE_RECIEVED_ACK_RETURNED=0x50,
	DATA_BYTE_RECIEVED_NOT_ACK_RETURNED=0x58,
	ARBITATION_LOST_DATA_LOST=0x38

}I2C_reply_t;

typedef enum{
	I2C_NOK,
	I2C_OK

}I2C_Error_t;


typedef struct{
	I2C_Bit_Rate_t bit_rate;

}I2C_cfg_t;



#endif /* I2C_I2C_TYPES_H_ */
